#!/usr/bin/env python3
"""
Test gRPC server for protosnoop verification.
Run: python3 server.py [--port 50051] [--tls]
"""
import argparse
import sys
import time
import concurrent.futures

import grpc
import test_pb2
import test_pb2_grpc

USERS = {
    1: test_pb2.User(
        id=1,
        name="Alice Smith",
        email="alice@example.com",
        address=test_pb2.Address(street="123 Main St", city="Springfield", country="US", zip=12345),
        tags=["admin", "beta-tester"],
    ),
    2: test_pb2.User(
        id=2,
        name="Bob Jones",
        email="bob@example.com",
        address=test_pb2.Address(street="456 Oak Ave", city="Shelbyville", country="US", zip=67890),
        tags=["user"],
    ),
    3: test_pb2.User(
        id=3,
        name="Carol White",
        email="carol@example.com",
        address=test_pb2.Address(street="789 Pine Rd", city="Capital City", country="US", zip=11111),
        tags=["user", "premium"],
    ),
}

ITEMS = [
    test_pb2.Item(id=1,  name="Widget A",    price=9.99,   status=test_pb2.ACTIVE,   data=b"\x01\x02\x03"),
    test_pb2.Item(id=2,  name="Gadget B",    price=24.95,  status=test_pb2.ACTIVE,   data=b"\x04\x05\x06\x07"),
    test_pb2.Item(id=3,  name="Doohickey C", price=4.50,   status=test_pb2.INACTIVE, data=b""),
    test_pb2.Item(id=4,  name="Thingamajig", price=149.00, status=test_pb2.ACTIVE,   data=b"\xff\xfe\xfd"),
    test_pb2.Item(id=5,  name="Whatchamacallit", price=0.99, status=test_pb2.UNKNOWN, data=b"hello"),
]


class TestServiceServicer(test_pb2_grpc.TestServiceServicer):

    def Echo(self, request, context):
        msg = (request.message + " ") * max(request.repeat, 1)
        return test_pb2.EchoResponse(
            message=msg.strip(),
            count=request.repeat,
            ok=True,
        )

    def GetUser(self, request, context):
        user = USERS.get(request.id)
        if user is None:
            context.abort(grpc.StatusCode.NOT_FOUND, f"user {request.id} not found")
        return user

    def ListItems(self, request, context):
        limit = request.limit if request.limit > 0 else len(ITEMS)
        items = ITEMS[:limit]
        return test_pb2.ListResponse(items=items, total=len(ITEMS))


def serve(port, use_tls, host="[::]"):
    server = grpc.server(concurrent.futures.ThreadPoolExecutor(max_workers=4))
    test_pb2_grpc.add_TestServiceServicer_to_server(TestServiceServicer(), server)

    if use_tls:
        # Self-signed certs (generated by gen-certs.sh if needed).
        try:
            with open("server.key", "rb") as f: key = f.read()
            with open("server.crt", "rb") as f: crt = f.read()
        except FileNotFoundError:
            print("TLS mode: server.key / server.crt not found. Run gen-certs.sh first.", file=sys.stderr)
            sys.exit(1)
        creds = grpc.ssl_server_credentials([(key, crt)])
        server.add_secure_port(f"{host}:{port}", creds)
        print(f"[server] listening on {host}:{port} (TLS)")
    else:
        server.add_insecure_port(f"{host}:{port}")
        print(f"[server] listening on {host}:{port} (plaintext)")

    print("[server] methods: Echo, GetUser, ListItems")
    print(f"[server] PID {__import__('os').getpid()}")

    server.start()
    try:
        server.wait_for_termination()
    except KeyboardInterrupt:
        server.stop(0)
        print("\n[server] stopped")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--port", type=int, default=50051)
    p.add_argument("--host", default="[::]", help="bind address (e.g. 0.0.0.0)")
    p.add_argument("--tls",  action="store_true", help="use TLS (requires server.key + server.crt)")
    args = p.parse_args()
    serve(args.port, args.tls, args.host)
