# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x0btestservice\".\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06repeat\x18\x02 \x01(\x05\":\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\n\n\x02ok\x18\x03 \x01(\x08\"E\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\x05\"d\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12%\n\x07\x61\x64\x64ress\x18\x04 \x01(\x0b\x32\x14.testservice.Address\x12\x0c\n\x04tags\x18\x05 \x03(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"b\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12#\n\x06status\x18\x04 \x01(\x0e\x32\x13.testservice.Status\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"\x1c\n\x0bListRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"?\n\x0cListResponse\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.testservice.Item\x12\r\n\x05total\x18\x02 \x01(\x05*/\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08INACTIVE\x10\x02\x32\xc7\x01\n\x0bTestService\x12;\n\x04\x45\x63ho\x12\x18.testservice.EchoRequest\x1a\x19.testservice.EchoResponse\x12\x39\n\x07GetUser\x12\x1b.testservice.GetUserRequest\x1a\x11.testservice.User\x12@\n\tListItems\x12\x18.testservice.ListRequest\x1a\x19.testservice.ListResponseb\x06proto3')

_STATUS = DESCRIPTOR.enum_types_by_name['Status']
Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
UNKNOWN = 0
ACTIVE = 1
INACTIVE = 2


_ECHOREQUEST = DESCRIPTOR.message_types_by_name['EchoRequest']
_ECHORESPONSE = DESCRIPTOR.message_types_by_name['EchoResponse']
_ADDRESS = DESCRIPTOR.message_types_by_name['Address']
_USER = DESCRIPTOR.message_types_by_name['User']
_GETUSERREQUEST = DESCRIPTOR.message_types_by_name['GetUserRequest']
_ITEM = DESCRIPTOR.message_types_by_name['Item']
_LISTREQUEST = DESCRIPTOR.message_types_by_name['ListRequest']
_LISTRESPONSE = DESCRIPTOR.message_types_by_name['ListResponse']
EchoRequest = _reflection.GeneratedProtocolMessageType('EchoRequest', (_message.Message,), {
  'DESCRIPTOR' : _ECHOREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testservice.EchoRequest)
  })
_sym_db.RegisterMessage(EchoRequest)

EchoResponse = _reflection.GeneratedProtocolMessageType('EchoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ECHORESPONSE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testservice.EchoResponse)
  })
_sym_db.RegisterMessage(EchoResponse)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testservice.Address)
  })
_sym_db.RegisterMessage(Address)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testservice.User)
  })
_sym_db.RegisterMessage(User)

GetUserRequest = _reflection.GeneratedProtocolMessageType('GetUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testservice.GetUserRequest)
  })
_sym_db.RegisterMessage(GetUserRequest)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testservice.Item)
  })
_sym_db.RegisterMessage(Item)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testservice.ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)

ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESPONSE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testservice.ListResponse)
  })
_sym_db.RegisterMessage(ListResponse)

_TESTSERVICE = DESCRIPTOR.services_by_name['TestService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=533
  _STATUS._serialized_end=580
  _ECHOREQUEST._serialized_start=27
  _ECHOREQUEST._serialized_end=73
  _ECHORESPONSE._serialized_start=75
  _ECHORESPONSE._serialized_end=133
  _ADDRESS._serialized_start=135
  _ADDRESS._serialized_end=204
  _USER._serialized_start=206
  _USER._serialized_end=306
  _GETUSERREQUEST._serialized_start=308
  _GETUSERREQUEST._serialized_end=336
  _ITEM._serialized_start=338
  _ITEM._serialized_end=436
  _LISTREQUEST._serialized_start=438
  _LISTREQUEST._serialized_end=466
  _LISTRESPONSE._serialized_start=468
  _LISTRESPONSE._serialized_end=531
  _TESTSERVICE._serialized_start=583
  _TESTSERVICE._serialized_end=782
# @@protoc_insertion_point(module_scope)
