#!/usr/bin/env python3
"""
Compile a .proto into schema.js — an ES module the snoop imports to decode
protobuf with field NAMES (and real scalar types) instead of bare field
numbers. yeet has no file IO, so we bake the schema into a module at build
time; this is the same pattern as generating vmlinux.h / *.bpf.o.

Usage:
    python3 tools/gen-schema.py demo/test.proto > schema.js

Requires grpcio-tools (provides grpc_tools.protoc + the protobuf runtime).
Run it with the poetry venv python from testservice/ if your system python
lacks it, e.g.:
    "$(cd testservice && poetry env info -p)/bin/python" tools/gen-schema.py ...
"""
import json
import os
import sys
import tempfile

from grpc_tools import protoc
from google.protobuf import descriptor_pb2 as d

TYPE = {
    1: "double", 2: "float", 3: "int64", 4: "uint64", 5: "int32",
    6: "fixed64", 7: "fixed32", 8: "bool", 9: "string", 10: "group",
    11: "message", 12: "bytes", 13: "uint32", 14: "enum",
    15: "sfixed32", 16: "sfixed64", 17: "sint32", 18: "sint64",
}
LABEL_REPEATED = 3


def field_entry(f):
    if f.type == 11 or f.type == 10:
        kind, typ = "message", f.type_name.lstrip(".")
    elif f.type == 14:
        kind, typ = "enum", f.type_name.lstrip(".")
    else:
        kind, typ = "scalar", TYPE.get(f.type, "bytes")
    return {
        "name": f.name,
        "kind": kind,
        "type": typ,
        "repeated": f.label == LABEL_REPEATED,
    }


def walk_message(msg, prefix, messages, enums):
    fq = f"{prefix}.{msg.name}" if prefix else msg.name
    messages[fq] = {
        "name": msg.name,
        "fields": {str(f.number): field_entry(f) for f in msg.field},
    }
    for en in msg.enum_type:
        enums[f"{fq}.{en.name}"] = {str(v.number): v.name for v in en.value}
    for nested in msg.nested_type:
        walk_message(nested, fq, messages, enums)


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen-schema.py <file.proto> [proto-include-dir]")
    proto = os.path.abspath(sys.argv[1])
    incdir = os.path.abspath(sys.argv[2]) if len(sys.argv) > 2 else os.path.dirname(proto)

    with tempfile.NamedTemporaryFile(suffix=".desc", delete=False) as tf:
        descset = tf.name
    rc = protoc.main([
        "", f"-I{incdir}",
        f"--descriptor_set_out={descset}", "--include_imports", proto,
    ])
    if rc != 0:
        sys.exit(f"protoc failed ({rc})")

    fds = d.FileDescriptorSet()
    with open(descset, "rb") as fh:
        fds.ParseFromString(fh.read())
    os.unlink(descset)

    messages, enums, rpc_types, pkg = {}, {}, [], ""
    for f in fds.file:
        prefix = f.package
        pkg = pkg or f.package
        for m in f.message_type:
            walk_message(m, prefix, messages, enums)
        for en in f.enum_type:
            fq = f"{prefix}.{en.name}" if prefix else en.name
            enums[fq] = {str(v.number): v.name for v in en.value}
        for svc in f.service:
            for meth in svc.method:
                rpc_types.append(meth.input_type.lstrip("."))
                rpc_types.append(meth.output_type.lstrip("."))

    schema = {
        "package": pkg,
        "rpcTypes": sorted(set(rpc_types)),
        "messages": messages,
        "enums": enums,
    }
    sys.stdout.write("// Generated by tools/gen-schema.py — do not edit by hand.\n")
    sys.stdout.write("export default ")
    json.dump(schema, sys.stdout, separators=(",", ":"))
    sys.stdout.write(";\n")


if __name__ == "__main__":
    main()
